version: '3.8'
services:
  db:
    image: postgres:15-alpine
    container_name: manejo_proyectos_sql
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data
      # ojo! deben estar en orden para que no se ejecute primero la creación del fixture
      # y luego las tablas sin tener la base de datos creada
      - ./init_db.sh:/docker-entrypoint-initdb.d/01_init_db.sh
      - ./10_ManejoProyectos_DDL_MySQL.sql:/docker-entrypoint-initdb.d/02_create_tables.sql
      - ./20_ManejoProyectos_Fixture_MySQL.sql:/docker-entrypoint-initdb.d/03_create_fixture.sql

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_container
    restart: always
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@phm.edu.ar
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
      - pgadmin-data:/var/lib/pgadmin

volumes:
  db:
  pgadmin-data:
