version: '3.8'
services:
  db:
    image: postgres:15-alpine
    container_name: manejo_proyectos_sql
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data
      - ./Docker/init_db.sh:/docker-entrypoint-initdb.d/init_db.sh
volumes:
  db:
    driver: local